### ISSUE TITLE
Test runner execution context

### ISSUE THREAD

**Issue by kyliau** [WebKit/Speedometer#12]
In our discussion so far we've determined that the test runner should have a default configuration for end users and a custom configuration for browser vendors / engineers.

# Default Configuration
The default configuration will be used by all end users and is not configurable by design.
This configuration should be
- fast (~5 minutes?)
- simple (just a run button, very much like [Speedometer v2](https://browserbench.org/Speedometer2.0/))
- consistent (used by all end users)

# Custom Configuration
The custom configuration is "hidden", and is accessible only by query parameters (more discussion needed. depending on how many flags there are we might want to use something different). 
This is useful for internal testing / research / CI / optimization. It would allow us to gather more in-depth data and try out new benchmarks / test runner features.

# Design Decisions
There are quite a few design decisions that we need to consider, and here's a few major ones that I can think of.
- Execution context (essentially iframe configuration, more on this later)
- Test iterations, setup / teardown procedures
- Scoring mechanism (algorithms like geometric mean vs arithmetic mean)

This issue focuses on execution context only, my thinking is that we can have a separate issue for each point.

## Execution Context
Since execution context is probably the one that requires most technical considerations, I'd like to kick off our discussion with that.
Execution context is essentially the iframe used to load a benchmark (aka workload) and its corresponding setup.

There are mainly two things to consider:
- same-origin vs cross-origin iframe
- sandboxed vs unrestricted iframe

### Same-origin vs cross-origin iframe
Same-origin iframe shares the same JavaScript context as the parent window.
It has unfettered access to `window.parent` and `window.parent.document`, and can load any external scripts.
Communication between parent window and iframe can happen programmatically without any extra work.

Pros of same-origin iframe:
- Simple (not much code involved)
- Can use Speedometer v2 as starter code
- Easy to deploy (no need for subdomains or a different port)

Cons of same-origin iframe:
- shares the same JavaScript context as the parent window (might have performance implications)
- not representative of how websites are usually loaded in a browser (via top-level navigation).

Cross-origin iframe has a `src` that points to either a different subdomain, different port, or different domain altogether (see [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy)).
Due to security reasons, cross-origin iframe has no access to the parent window and is not allowed to modify the parent's DOM. To achieve this, cross-origin `iframe` has its own stack, heap, and message queue, effectively running in its own [runtime](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#several_runtimes_communicating_together) and can only communicate through sending messages via the `postMessage` method.

Pros of cross-origin iframe:
- More representative of real world navigation
- Isolated JavaScript context
- Can use Grand Prix as starter code

Cons of cross-origin iframe:
- Requires some form of RPC via [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). Communication must be bi-directional because parent window needs to send test operations to iframe, and iframe needs to report test results back to parent window. Care must be taken to not include RPC overhead in test measurements.
- More complex deployment (need to deploy each benchmark to a different origin)
- More involved test runner architecture

#### Sandboxed vs unrestricted iframe

Apart from same-origin and cross-origin `src`, iframe also has the [`sandbox`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) attribute which applies extra restrictions to the content in the frame.
This means we can use the same origin for each benchmark but have each of them run in an isolated JavaScript context.
If our architecture supports cross-origin iframe, then we can also support sandboxing without too much work.
Otherwise, we'll need to implement similar RPC mechanism as cross-origin iframe to facilitate bi-directional communication. 
It is worth noting that modern versions of Chrome, Firefox, and Safari all [support](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#browser_compatibility) this attribute. As of August 2022, `<iframe sandbox>` does not currently construct an out-of-process iframe in _any_ browser, even if the iframe is cross-origin (according to Jason, the original author of Grand Prix).

Pros of sandboxed iframe
- Isolated JavaScript context
- Can use Grand Prix as starter code
- Straight-forward deployment, all benchmarks can be hosted on the same origin

Cons of sandboxed iframe
- Requires RPC
- Need to avoid overhead of async communication in test measurements

# Thoughts
In our discussion so far, it looks like we are pivoting towards same-origin iframe for default configuration, but we'd like to support cross-origin iframe in custom configuration. I think this is a good setup to start with because it'd allow us to bootstrap the default test runner relatively easily, while allowing us to experiment and gather more data with cross-origin / sandboxed iframe in custom configuration to gauge how much impact it has on the test results. 
That said, the test runner architecture will be quite different if we choose to support cross-origin iframe, so we ought to make this decision very early on, even if we don't plan to use cross-origin iframe in the default config.

**Comment by rniwa** [comment]
I'm going to reiterate that I don't think we should support cross-origin frames at all. It adds a ton of complexity for a very questionable benefit. In practice, the performance of an iframe and non-iframe content should be more or less the same.

Since WebKit hasn't implemented site isolation per process, using cross-origin iframe would result in a totally different performance characteristics between Blink/Gecko and WebKit. I don't think we want to have that.

**Comment by kyliau** [comment]
@rniwa totally understand that, and in fact I think we should start with same-origin iframe to get things going. However, would you support cross-origin iframe in _custom_ configuration?
That's the crux I'm trying to highlight here, because we'll still need the code in there for custom configuration if we want to support that. Do you think the complexity in the codebase is worthwhile for something that's not default?
On a similar note, what's your stance on sandboxed iframe from Safari's perspective?

> the performance of an iframe and non-iframe content should be more or less the same.

I'm hoping we could gather some numbers for this from the custom configuration to help us make a more objective assessment.

**Comment by rniwa** [comment]
> However, would you support cross-origin iframe in custom configuration?

I'm afraid not. Sending messages back & forth between frames will amount to a massive increase in the complexity of the benchmark harness. It's pretty important that the harness stays simple so that we easily reason about it.

Just consider the fact 5ms timer throttling issue in the test harness, for which we just released Speedometer 2.1, wasn't even known until early this year despite of the fact browser engineers have been looking into optimizing Speedometer for years. We've also had an instance in which WebKit/JSC was able to finish SunSpider so fast that CPU started throttling between test cases and made the overall test score worse for WebKit/JSC. Another browser engine was avoiding this problem because it had loading animation which kept CPU "hot" between test cases. Things like that is very hard to reason even in the simplest of example, and the more harness code we have, the harder it becomes to reason about.

**Comment by LeszekSwirski** [comment]
I, on the other hand, feel very strongly that cross origin should not only be available, but be the default - also for reasons of being able to easily reason about the performance characteristics. We've observed too often the performance impact of same origin non-isolated information (caches, startup costs, etc) leaking across runs that were supposed to be independent, and avoiding this leakage is just as important as any other concern if we want to measure something realistic.

Yes, Safari doesn't currently implement site isolation, do performance characteristics between WebKit and Blink/Gecko will differ, but a) most likely it eventually will, and b) this is effectively a browser implementation detail that has an effect on performance and _should_ be reflected in the benchmark.

I don't consider complexity of the runner to be equivalent to complexity of reasoning about the runs. Microbenchmarks have the simplest runners (loops) and the least simple reasoning (like the sunspider throttling example you mentioned). Consider the setTimeout issue - we needed to add a recursion breaking rAF, an additional complication to the runner, because the setTimeout nesting was leaking across runs. I see this as an argument for heavier iframe isolation, not against it.

**Comment by smaug----** [comment]
My gut feeling is that some way to test cross-origin handling would be good. However, usually the most interesting part of cross origin pages is the top level page loading cross origin iframes, during its own page load, that is where various caches tend to matter the most.
And I don't think we're planning to have page load tests in this benchmark.
So I think it would be good to have some concrete examples where cross origin handling matters.
postMessage handling is one such case, but are there real world cases where cross origin postMessage performance is particularly important?



> `<iframe sandbox>` does not currently construct an out-of-process iframe in _any_ browser, even if the iframe is cross-origin

I don't think this is correct.

**Comment by kyliau** [comment]
> My gut feeling is that some way to test cross-origin handling would be good. However, usually the most interesting part of cross origin pages is the top level page loading cross origin iframes, during its own page load, that is where various caches tend to matter the most.

I don't think we care too much about cross-origin handling per se, it's just that cross-origin loading provides certain guarantees, one of them being isolated execution context, which is really what we are after.
That's why in lieu of cross-origin iframe, sandboxed iframe could be a viable candidate for this purpose.
You brought up a really good point about caches - I don't have enough insights into how they're being shared across windows (test runner and the benchmark), but that's definitely something worth investigating.

> Sounds like we may have a fundamental disagreement regarding this. We may need to schedule a meeting to discuss this.

A meeting to discuss this in depth is certainly a good idea, I hope this thread provides enough context before we jump into the details. I'll coordinate with you all on Slack and set something up.

**Comment by rniwa** [comment]
> I don't think we care too much about cross-origin handling per se, it's just that cross-origin loading provides certain guarantees, one of them being isolated execution context, which is really what we are after.

That is only true in Gecko & Blink. While WebKit does have a plan to implement site isolation of some kind (it's yet to be seen whether it's going to be process per site or something else), I don't think that's happening anytime soon, and not certainly within the timeframe we'd be lookin to work on this benchmark (i.e. next 12-18 months).

**Comment by rniwa** [comment]
> Yes, Safari doesn't currently implement site isolation, do performance characteristics between WebKit and Blink/Gecko will differ, but a) most likely it eventually will, and b) this is effectively a browser implementation detail that has an effect on performance and should be reflected in the benchmark.

That's not a guaranteed outcome and we certainly don't want to commit to such a development.

Given navigating across multiple  origins in a single iframe isn't known to be important for web app responsive, I have a hard time entertaining such a suggestion.

**Comment by rniwa** [comment]
> However, usually the most interesting part of cross origin pages is the top level page loading cross origin iframes, during its own page load, that is where various caches tend to matter the most. And I don't think we're planning to have page load tests in this benchmark.

Right, we certainly don't want to scope creep this benchmark. It's rather critical that we stick to what we're trying to measure here: web app responsiveness.

**Comment by LeszekSwirski** [comment]
> However, usually the most interesting part of cross origin pages is the top level page loading cross origin iframes, during its own page load, that is where various caches tend to matter the most. And I don't think we're planning to have page load tests in this benchmark.

While the intention of this benchmark, like with S2, is to measure interactivity rather than page load, any reasonably short running non-micro benchmark is still going to have load-like warm up behaviour, and we've found S2 to behave a lot like a loading benchmark in past analyses. There's more to caches than loading speed anyway; one concrete example I can think of is lazy function compilation, where the first iteration of a benchmark will perform lazy compilations and subsequent suite runs may or may not drop those compilation results before the next iteration of said benchmark. We've noticed differences in S2 score when adjusting cache retention heuristics, and we really shouldn't have.

> Given navigating across multiple origins in a single iframe isn't known to be important for web app responsiveness, I have a hard time entertaining such a suggestion.

This is a fair comment, but it's arguing against a different point than I'm making; I'm saying that we should try to isolate the runs from each other as much as possible. Navigating between wildly different apps or different framework implementations on the same origin is also not standard browsing behaviour.

> While WebKit does have a plan to implement site isolation of some kind (it's yet to be seen whether it's going to be process per site or something else), I don't think that's happening anytime soon, and not certainly within the timeframe we'd be lookin to work on this benchmark (i.e. next 12-18 months).

Fair, OTOH I hope that the lifetime of this benchmark is longer than it's development time.

**Comment by rniwa** [comment]
Is there anything left here to discuss for v3?

**Comment by bgrins** [comment]
> Is there anything left here to discuss for v3?

I think it can close. As in #9, there's some valuable discussion here but I don't think any action needed at this point.
