### ISSUE TITLE
Latest Speedometer 3.0 is broken on Safari

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#179]
I'm getting this error in NewsSite-Next:

```
[Error] TypeError: null is not an object (evaluating 'page.querySelector("#navbar-dropdown-toggle").click')
	(anonymous function) (tests.mjs:372)
	_runTest (benchmark-runner.mjs:291)
	(anonymous function) (benchmark-runner.mjs:276)
```

**Comment by rniwa** [comment]
Fixed in https://github.com/WebKit/Speedometer/pull/180

**Comment by rniwa** [comment]
I think we need to rewrite some of these tests to not use replaceState.

**Comment by flashdesignory** [comment]
that security "feature" is really not ideal for us 😄 

I think it might be the hash routers from react-router-dom that cause the issue. 
We have that module in all the react-based apps, but only need it in the news-site (since that's the only test that actually navigates). 

We don't test the filters (all, active, complete) in the todoMVC apps and another band-aid might be to remove those  filters instead. 

@rniwa since I can't replicate the bug, what happens if you omit a todomvc react based test? 
Does it pass?

@julienw - you're pretty much reviewed all the workload updates, any other ideas besides the potential culprit being the react-router-dom?

**Comment by bgrins** [comment]
It'd be great if someone familiar with WebKit could log out how many times each individual test is calling replaceState to help narrow down the problem and what change would have the most impact.

**Comment by rniwa** [comment]
Fixed by https://github.com/WebKit/Speedometer/pull/182

**Comment by rniwa** [comment]
Tracking this overarching issue as https://bugs.webkit.org/show_bug.cgi?id=257269.

**Comment by rniwa** [comment]
It's broken because of complex-static-html again :(

**Comment by rniwa** [comment]
I landed a WebKit side fix in https://commits.webkit.org/264499@main.
