### ISSUE TITLE
Update ToDoMVC tests

### ISSUE THREAD

**Issue by rniwa** [WebKit/Speedometer#3]
Update ToDoMVC to use the latest versions of frameworks.

**Comment by rniwa** [comment]
We currently use the following set of ToDoMVC examples:

 - VanillaJS
 - React
 - EmberJS
 - ~EmberJS-Debug~
 - BackboneJS
 - AngularJS
 - Angular2-TypeScript
 - VueJS
 - jQuery
 - Preact
 - Inferno
 - Elm
 
 I think it's time to finally retire EmberJS-Debug. Which one should be added & which one should be retired for v3?

**Comment by rniwa** [comment]
> Do we want to take a data-driven (e.g. look at adoption levels) look at what's currently popular to guide our decision making for what to drop? e.g. may be worth checking on Backbone and Inferno

It would be good if we can do data-driven look. Do you have any suggestions on how to gather such data?

**Comment by addyosmani** [comment]
> Hm... it doesn't have a license. Can we ask them to add licensing terms?
Good catch! I've requested that Rich add a LICENSE file to their repo. 

> Cross posting here. Including Polymer might be useful since it's still used by YouTube and it makes extensive use of web component features, which are used on many popular websites these days.

I would be open to this. My understanding is the Polymer team recommend using https://lit.dev/ (same team) these days but can find out if YouTube plans on sticking with the old version or moving over to this library soon.

**Comment by kyliau** [comment]
Here's a snapshot of the `httparchive.technologies.2022_05_12_{desktop, mobile}` table showing # origins using JS framework / library of interest:

<img width="1050" alt="Screen Shot 2022-06-08 at 3 53 48 PM" src="https://user-images.githubusercontent.com/2941178/172730824-c061ef76-e711-4246-9c3f-86a5cf9ae3a8.png">

**Comment by juliandescottes** [comment]
It's great to have this data, thanks for sharing! 

Overall, since we want to include more than just Todo MVC apps here, I wonder if we should be careful about the similarities of the frameworks we pick for TodoMVC? (exaggerating) If all popular frameworks are all virtual dom based, and mostly differ from a developer ergonomics point of view, the benchmark would strongly be biased in favor of a single family of frameworks. 

To take a practical example, in the current list there is React/React-redux/Preact. With speedometer 2, was it valuable to have those 3, or did they roughly regress/improve at the same time?

I think it's still healthy to have a few representatives of each framework family, but this might be worth keeping in mind when reviewing the final selection.

**Comment by shvaikalesh** [comment]
> We currently use the following set of ToDoMVC examples:

I believe we also use Flight?

> What else should be added

For the JSC team, it would be very much useful to have subtests capturing modern JS features like:

  * Vue 3.0 and [RP]eact + MobX that heavily use `Proxy`;
  * Angular app with lots of private fields;
  * some crypto stuff that leverages `BigInt`.

+1 on web components.

> retired for v3

Definitely Inferno, Elm, Flight. Those were quite niche when Speedo2 was created, and now they are plain dead judging by latest release and weekly downloads on npm:

  * https://www.npmjs.com/package/inferno
  * https://www.npmjs.com/package/flightjs
  * https://www.npmjs.com/package/elm

**Comment by rniwa** [comment]
So it looks like we can retire EmberJS-Debug, Inferno, Elm, and Flight:
* VanillaJS
* Vanilla-ES2015
* React
* React-Redux
* EmberJS
* ~EmberJS-Debug~
* BackboneJS
* AngularJS
* Angular2-TypeScript
* VueJS
* jQuery
* Preact
* ~Inferno~
* ~Elm~
* ~Flight~

And we somehow want to add the following frameworks but they don't have ToDoMVC examples:
* nuxt.js
* next.js
* lit-html
* Svelte

**Comment by kyliau** [comment]
Nuxt and Next.js are meta-frameworks for Vue and React, respectively. 
Do we want to consider "framework families" like @juliandescottes suggested?

It might be worthwhile to differentiate library vs framework.
There are many ways to build an application with a library, but frameworks like Next.js and Nuxt often offer a prescribed way to build things in a more efficient manner (bundling, code splitting, minification, etc out of the box).

On another note, AngularJS has been officially deprecated. Although it's still popular, I think we should just drop it in favor of Angular2 since they belong in the same "family".

**Comment by rniwa** [comment]
What's the angular mentioned in https://github.com/WebKit/Speedometer/issues/3#issuecomment-1150492924? Is it angular 2? or angular.js. We should pick whichever is most popular.

**Comment by rniwa** [comment]
> It's Angular (also known as Angular-Typescript or Angular 2).

That is an evidence for only including Angular 2.

> Long term support (LTS) for AngularJS [ended](https://blog.angular.io/discontinued-long-term-support-for-angularjs-cc066b82e65a) on December 31, 2021.

Just for completeness, I don't think whether something is deprecated or actively maintained is relevant so long as it's use is prevalent.

**Comment by kyliau** [comment]
> Just for completeness, I don't think whether something is deprecated or actively maintained is relevant so long as its use is prevalent.

I agree with this in a broad sense, but we ought to keep in mind that the deprecated status of a library or framework likely means that some of the best practice guidelines might no longer be applicable, the tool to build the application might be out of date / unmaintained, and it'll increase our maintenance burden down the road.

I think it's down to the cost-benefit analysis of prevalence vs maintenance.

For jQuery, even if it's getting less popular, it makes sense to include it because it's just so prevalent.
For AngularJS, the adoption is much lower compared to jQuery, and there is a similar successor (Angular) in place, so it's likely not worth the extra burden.

**Comment by rniwa** [comment]
> > Just for completeness, I don't think whether something is deprecated or actively maintained is relevant so long as its use is prevalent.
> 
> I agree with this in a broad sense, but we ought to keep in mind that the deprecated status of a library or framework likely means that some of the best practice guidelines might no longer be applicable, the tool to build the application might be out of date / incompatible with the runtime, and it'll increase our maintenance burden down the road.

That's irrelevant. So long as a library or a framework is widely used, we need to figure out a way to incorporate into our benchmark. Maintenance cost of benchmark is just about the lowest priority.

**Comment by rniwa** [comment]
Existing:
* VanillaJS
* Vanilla-ES2015
* React
* React-Redux
* EmberJS
* ~EmberJS-Debug~
* BackboneJS
* ~AngularJS~
* Angular2-TypeScript
* VueJS
* jQuery
* Preact
* ~Inferno~
* ~Elm~
* ~Flight~

Want to add:
* nuxt.js
* next.js
* lit-html
* Svelte

**Comment by vprelovac** [comment]
Couple of things to consider:

1.  By testing JS frameworks, the benchmark measures the level of engine's adaptation to performance issues arisen from poorly coding the framework. In other words, some engines can achieve better performance by specifically targetting poorly written code in those frameworks. 

2. Choosing just one simple practical implementation (ToDoMVC) drastically reduces the breadth and scope of actual JS functionality that the test ends up measuring. Such narrow scope can then be easilly optimized using LTO/PGO, resulting in a engine fast at doing a very small subset of JS while potentially slower at anything outside of that scope. The web can not be approximated by a simple todo app.

3. Instead perhaps focus on benchmarking atomic level JS functions, that all these frameworks will be using anyway.

**Comment by bgrins** [comment]
Alright, I think this can close now. I landed the change to remove relevant tests in #49. Spun out a separate task to update frameworks for existing tests into #50, and to add the new tests in #51 and #52.

@vprelovac yes, one of the major goals for the project is to reflect more real-world workloads beyond todomvc, but we're carrying over some of the tests from Speedometer 2 as a starting point. Re "atomic" - our goal is to benchmark end to end journeys (outlined in https://github.com/WebKit/Speedometer#what-is-speedometer), since we think that's the best way to make improvements to the benchmark show up for actual people using browsers. There's good background on the motivation for that and challenges with testing single functions in https://webkit.org/blog/3395/speedometer-benchmark-for-web-app-responsiveness/
